### PR TITLE
MonadFail instance for GHC 8.6

### LINKED ISSUE #21: MonadFail compatibility
Trying to build the current package with GHC-8.6, I get:
```
[13 of 31] Compiling Graphics.PDF.Draw ( Graphics/PDF/Draw.hs, dist/build/Graphics/PDF/Draw.o )

Graphics/PDF/Draw.hs:256:5: error:
    • No instance for (Control.Monad.Fail.MonadFail Draw)
        arising from a do statement
        with the failable pattern ‘(x : xs)’
    • In a stmt of a 'do' block: (x : xs) <- gets supplyNames
      In the expression:
        do (x : xs) <- gets supplyNames
           modifyStrict $ \ s -> s {supplyNames = xs}
           return x
      In an equation for ‘supplyName’:
          supplyName
            = do (x : xs) <- gets supplyNames
                 modifyStrict $ \ s -> ...
                 return x
    |
256 |     (x:xs) <- gets supplyNames
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build HPDF-1.4.10 (which is required by exe:tttool from
tttool-1.8).
```
It would be great to have HPDF with current versions of GHC, as `tttool` heavily relies on it.

### PR DESCRIPTION
**Pull request by mtolly**
Closes #21 

CPP-limited to `base` 4.9.0.0 and up based on the info [here](http://hackage.haskell.org/package/base-4.12.0.0/docs/Control-Monad-Fail.html).

### CODE REVIEW

**Comment by nomeata** [comment]
@mtolly, do you have an interest in maybe taking over maintainership of HPDF on hackage?

**Comment by dten** [comment]
won't compile for me with base-4.10.1.0
```
Graphics/PDF/Draw.hs:204:27: error:
        • No instance for (Fail.MonadFail (ST s))
            arising from a use of ‘Fail.fail’
        • In the expression: Fail.fail s
          In the second argument of ‘($)’, namely ‘\ _ -> Fail.fail s’
          In the expression: Draw $ \ _ -> Fail.fail s
        |
    204 |     fail s = Draw $ \_ -> Fail.fail s
        |                           ^^^^^^^^^^^
```

**Comment by dten** [comment]
works with base-4.11.1.0

ST isn't monad fail until 4.11
https://www.stackage.org/haddock/lts-11.22/base-4.10.1.0/Control-Monad-ST.html#t:ST
https://www.stackage.org/haddock/lts-12.14/base-4.11.1.0/Control-Monad-ST.html#t:ST

suggestion here is also `(4,11,0)`
https://wiki.haskell.org/MonadFail_Proposal

**Comment by mtolly** [comment]
Thanks @dten, I've edited the commit with that. Though it looks like #23 would be a better change to use; the MonadFail instance is overkill since it was only used for one failing `do` pattern.

@nomeata Tbh I probably wouldn't be the best person - I could maybe keep up with basic compiler fixes and that sort of thing but I don't know much of anything about the PDF format internals.

**Comment by dten** [comment]
That pr has a lot more changes in it. Your change worked and I was easy to verify 👍

File: Graphics/PDF/Draw.hs [hunk 1]
```diff
@@ -186,6 +189,11 @@ instance Monad Draw where
                           unDraw (f a) env
     return x = Draw $ \_env -> return x
 
+#if MIN_VERSION_base(4,11,0)
+instance Fail.MonadFail Draw where
+    fail s = Draw $ \_ -> Fail.fail s
```
Comment (bgohla) [inline Graphics/PDF/Draw.hs:194]: in my view this is the wrong way to go. the reason the original code was actually fine, was that the list is defined to be infinite, so that should be expressed by using, e.g., http://hackage.haskell.org/package/inflist-0.0.1/docs/src/Data-InfList.html#InfList

i've implemented that here: https://github.com/alpheccar/HPDF/pull/27

**Comment by hsyl20** [comment]
Fixed in 1.5.0
